function schemaForFields(fields) {
  const properties = {};
  const required = [];
  for (const field of fields || []) {
    properties[field.name] = { type: 'string', description: `${field.name} supplied in the ${field.location}.` };
    if (field.required) required.push(field.name);
  }
  return { type: 'object', properties, ...(required.length ? { required } : {}) };
}

function openApiDocument(analysis) {
  const enrichmentById = new Map((analysis.enrichments || []).map(item => [item.endpointId, item.enrichment]));
  const paths = {};
  for (const route of analysis.routes) {
    const operation = {
      operationId: route.id,
      summary: enrichmentById.get(route.id)?.summary || route.summary,
      description: enrichmentById.get(route.id)?.description || route.description,
      tags: [route.path.split('/').filter(Boolean)[1] || 'default'],
      responses: {},
      'x-docforge': { sourceFile: route.sourceFile, sourceLine: route.sourceLine, confidence: route.confidence, integrations: route.integrations },
    };
    const parameters = (route.requestFields || []).filter(f => f.location !== 'body').map(field => ({ name: field.name, in: field.location, required: field.required, schema: { type: 'string' } }));
    if (parameters.length) operation.parameters = parameters;
    const bodyFields = (route.requestFields || []).filter(f => f.location === 'body');
    if (bodyFields.length) operation.requestBody = { required: bodyFields.some(f => f.required), content: { 'application/json': { schema: schemaForFields(bodyFields) } } };
    for (const response of route.responses.length ? route.responses : [{ status: 200, fields: [] }]) {
      operation.responses[String(response.status)] = { description: response.status >= 400 ? 'Error response.' : 'Successful response.', ...(response.fields.length ? { content: { 'application/json': { schema: { type: 'object', properties: Object.fromEntries(response.fields.map(name => [name, { type: 'string' }])) } } } } : {}) };
    }
    paths[route.path] = { ...(paths[route.path] || {}), [route.method.toLowerCase()]: operation };
  }
  return { openapi: '3.0.3', info: { title: `${analysis.project.name} API`, version: '0.1.0', description: 'Generated by DocForge from source analysis.' }, servers: [{ url: 'http://localhost:5000' }], paths, 'x-docforge': { stack: analysis.stack, environmentVariables: analysis.environmentVariables, generatedAt: analysis.project.analyzedAt } };
}

function markdownDocument(analysis) {
  const lines = [`# ${analysis.project.name} API`, '', '> Generated by DocForge from source analysis.', '', '## Stack', '', ...analysis.stack.map(item => `- ${item}`), '', '## Endpoints', ''];
  for (const route of analysis.routes) {
    lines.push('### `' + route.method + ' ' + route.path + '`', '', route.description, '', '- Source: `' + route.sourceFile + ':' + route.sourceLine + '`', '- Integrations: ' + (route.integrations.length ? route.integrations.join(', ') : 'None detected'));
    if (route.requestFields.length) { lines.push('', 'Request fields:', ''); for (const field of route.requestFields) lines.push('- `' + field.name + '` (' + field.location + ')' + (field.required ? ' — required' : '')); }
    lines.push('', 'Responses:', '');
    for (const response of route.responses) lines.push('- `' + response.status + '`' + (response.fields.length ? ' — ' + response.fields.map(f => '`' + f + '`').join(', ') : ''));
    if (route.frontendConsumers?.length) lines.push('', 'Frontend consumers: ' + route.frontendConsumers.map(c => '`' + c.sourceFile + ':' + c.sourceLine + '`').join(', '));
    lines.push('');
  }
  lines.push('## Configuration', '', ...(analysis.environmentVariables.length ? analysis.environmentVariables.map(name => '- `' + name + '`') : ['No environment variables detected.']), '', '## Warnings', '', ...(analysis.warnings.length ? analysis.warnings.map(w => '- ' + w) : ['None detected.']), '');
  return lines.join('\n');
}

module.exports = { openApiDocument, markdownDocument };
