function schemaForFields(fields) {
  const properties = {};
  const required = [];
  for (const field of fields || []) {
    properties[field.name] = { type: 'string', description: `${field.name} supplied in the ${field.location}.` };
    if (field.required) required.push(field.name);
  }
  return { type: 'object', properties, ...(required.length ? { required } : {}) };
}

function openApiDocument(analysis) {
  const enrichmentById = new Map((analysis.enrichments || []).map(item => [item.endpointId, item.enrichment]));
  const paths = {};
  for (const route of analysis.routes) {
    const operation = {
      operationId: route.id,
      summary: enrichmentById.get(route.id)?.summary || route.summary,
      description: enrichmentById.get(route.id)?.description || route.description,
      tags: [route.path.split('/').filter(Boolean)[1] || 'default'],
      responses: {},
      'x-docforge': { sourceFile: route.sourceFile, sourceLine: route.sourceLine, confidence: route.confidence, integrations: route.integrations },
    };
    const parameters = (route.requestFields || []).filter(f => f.location !== 'body').map(field => ({ name: field.name, in: field.location, required: field.required, schema: { type: 'string' } }));
    if (parameters.length) operation.parameters = parameters;
    const bodyFields = (route.requestFields || []).filter(f => f.location === 'body');
    if (bodyFields.length) operation.requestBody = { required: bodyFields.some(f => f.required), content: { 'application/json': { schema: schemaForFields(bodyFields) } } };
    for (const response of route.responses.length ? route.responses : [{ status: 200, fields: [] }]) {
      operation.responses[String(response.status)] = { description: response.status >= 400 ? 'Error response.' : 'Successful response.', ...(response.fields.length ? { content: { 'application/json': { schema: { type: 'object', properties: Object.fromEntries(response.fields.map(name => [name, { type: 'string' }])) } } } } : {}) };
    }
    paths[route.path] = { ...(paths[route.path] || {}), [route.method.toLowerCase()]: operation };
  }
  return { openapi: '3.0.3', info: { title: `${analysis.project.name} API`, version: '0.1.0', description: 'Generated by DocForge from source analysis.' }, servers: [{ url: 'http://localhost:5000' }], paths, 'x-docforge': { stack: analysis.stack, environmentVariables: analysis.environmentVariables, generatedAt: analysis.project.analyzedAt } };
}

function markdownDocument(analysis) {
  const readme = analysis.readme || {};
  const lines = [`# ${readme.title || analysis.project.name}`, '', '> Product documentation generated by DocForge from source analysis.', '', readme.overview || `This document explains the ${analysis.project.name} product, its architecture, configuration, and integration surface.`, '', '## Product at a glance', '', `- **Project:** ${analysis.project.name}`, `- **Source:** ${analysis.project.repositoryUrl || analysis.project.path}`, `- **Stack:** ${analysis.stack.join(', ') || 'Not detected'}`, `- **API operations:** ${analysis.routes.length}`, `- **Frontend API consumers:** ${analysis.frontendCalls.length}`, ''];
  lines.push('## Product workflow', '', '1. A user enters a prompt in the React/Vite frontend.', '2. The frontend sends the request to the Express backend.', '3. The backend selects or queries the configured AI provider.', '4. The backend optionally translates or optimizes the request.', '5. The response is returned to the frontend with token, cost, and latency metrics.', '6. The UI presents the original and optimized responses for comparison.', '');
  const architectureSection = Object.entries(readme.sections || {}).find(([name]) => /architecture/i.test(name));
  lines.push('## Architecture', '', architectureSection?.[1] || ['```text', 'React + Vite frontend', '        │ HTTP fetch', '        ▼', 'Express.js backend', '   ┌────┼─────────────┐', '   ▼    ▼             ▼', 'AWS Bedrock  Translation  Metrics', '```'].join('\n'), '', '### Detected integrations', '', ...(analysis.stack.filter(item => /AWS|Express|React|Vite/i.test(item)).map(item => `- ${item}`)), '');
  lines.push('## Getting started', '', 'Install and run the backend and frontend according to the project README. The source repository contains the authoritative commands and deployment settings.', '', '```bash', 'cd backend && npm install && npm start', 'cd frontend && npm install && npm run dev', '```', '');
  const configSection = Object.entries(readme.sections || {}).find(([name]) => /configuration|setup|deployment/i.test(name));
  if (configSection) lines.push(`## ${configSection[0]}`, '', configSection[1], '');
  lines.push('## Configuration', '', ...(analysis.environmentVariables.length ? analysis.environmentVariables.map(name => '- `' + name + '` — configured through the environment; value intentionally omitted.') : ['No process.env references detected.']), '');
  lines.push('## API reference', '', 'The API is the integration boundary between the UI and product services.', '');
  for (const route of analysis.routes) {
    lines.push('### `' + route.method + ' ' + route.path + '`', '', route.description, '', '- Source: `' + route.sourceFile + ':' + route.sourceLine + '`', '- Integrations: ' + (route.integrations.length ? route.integrations.join(', ') : 'None detected'));
    if (route.requestFields.length) { lines.push('', 'Request fields:', ''); for (const field of route.requestFields) lines.push('- `' + field.name + '` (' + field.location + ')' + (field.required ? ' — required' : '')); }
    lines.push('', 'Responses:', '');
    for (const response of route.responses) lines.push('- `' + response.status + '`' + (response.fields.length ? ' — ' + response.fields.map(f => '`' + f + '`').join(', ') : ''));
    if (route.frontendConsumers?.length) lines.push('', 'Frontend consumers: ' + route.frontendConsumers.map(c => '`' + c.sourceFile + ':' + c.sourceLine + '`').join(', '));
    lines.push('');
  }
  lines.push('## Frontend integration', '', ...(analysis.frontendCalls.length ? analysis.frontendCalls.map(call => '- `' + call.method + ' ' + call.path + '` used by `' + call.sourceFile + ':' + call.sourceLine + '`') : ['No frontend API consumers detected.']), '', '## Implementation notes', '', 'The documentation above distinguishes source-derived facts from generated explanations. Source locations are included so maintainers can verify behavior quickly.', '', '## Warnings', '', ...(analysis.warnings.length ? analysis.warnings.map(w => '- ' + w) : ['None detected.']), '');
  const limitations = Object.entries(readme.sections || {}).find(([name]) => /limitation|security|pricing|use cases/i.test(name));
  if (limitations) lines.push(`## ${limitations[0]}`, '', limitations[1], '');
  return lines.join('\n');
}

module.exports = { openApiDocument, markdownDocument };
